TOKEN_BYTES = 24
IDENTIFIER_BYTES = 24
NONCE_BYTES = 24
PUBLICKEY_BYTES = 32
SHA512HASH_BYTES = 64

PACKET_ID_REGISTRATION_REQUEST = 10
PACKET_ID_REGISTRATION_REQUEST_ACK = 11
PACKET_ID_REGISTRATION_TOKEN = 12
PACKET_ID_REGISTRATION_TOKEN_ACK = 13

PACKET_ID_UPDATE_PK_REQUEST = 20
PACKET_ID_UPDATE_PK_RESPONSE = 21
PACKET_ID_UPDATE_PK_SEND_DATA = 22
PACKET_ID_UPDATE_PK_SEND_DATA_ACK = 23

PACKET_ID_SEND_MSG = 30
PACKET_ID_SEND_MSG_RESPONSE = 31
PACKET_ID_SEND_MSG_DATA = 32
PACKET_ID_SEND_MSG_DATA_ACK = 33

PACKET_ID_RECV_MSG = 40
PACKET_ID_RECV_MSG_RESPONSE = 41

STORAGE_REGISTRATION_DIR = 'storage/pending_registrations/'
STORAGE_PIR_DIR = 'storage/pir/'
STORAGE_CHANNELS_DIR = 'storage/channels/'
HTTP_STATIC_DIR = 'html/'

TOR_SOCKS_PORT = 7001
TOR_CONTROL_PORT = 9051
DEFAULT_REG_SERVER_PORT = 8900
